### PR TITLE
Backend/scene control

### PR DESCRIPTION
**Pull request by RohitK-RIT**
## Summarize what is being added

Scene transition system.
## Please describe how to test

1. Play Assets/_Project/Scenes/Title Scene.unity scene.
2. In 2.5s your scene should first load the loading scene additively and then load the requested scene.

## Relevant Screenshots

Character Portrait Button Click

## Issue worked on

https://timeisup.atlassian.net/browse/SCRUM-22?atlOrigin=eyJpIjoiNmJmMmRjMWYwM2Y0NGM4NWFkNjA0NmQyMDk0NWUyZWEiLCJwIjoiaiJ9
## What Sprint is this due in?

Sprint 2

### CODE REVIEW

**Review by heenathadani — COMMENTED** [review]
do we need another title scene for just one screen. What I mean to say is the Test_UI scene already has this title screen. 
is it possible we do the functionality you've put in title scene to apply to test_UI > canvas > title screen ?

**Comment by RohitK-RIT** [comment]
> do we need another title scene for just one screen. What I mean to say is the Test_UI scene already has this title screen. is it possible we do the functionality you've put in title scene to apply to test_UI > canvas > title screen ?

It surely is possible. I've created a title scene, as shown here, to show the transition from one scene to another (which means it is unnecessary to use these scenes only). The system is flexible and can load any scene in the build settings of the project.

**Comment by heenathadani** [comment]
> > do we need another title scene for just one screen. What I mean to say is the Test_UI scene already has this title screen. is it possible we do the functionality you've put in title scene to apply to test_UI > canvas > title screen ?
> 
> It surely is possible. I've created a title scene, as shown here, to show the transition from one scene to another (which means it is unnecessary to use these scenes only). The system is flexible and can load any scene in the build settings of the project.

Alirghty, approved.

**Review by heenathadani — APPROVED** [review]

**Review by roosa2000 — APPROVED** [review]
Approved

**Pull request merged**
